package learning

import org.apache.spark.sql.SQLContext
import org.apache.spark.{SparkConf, SparkContext}


/**
 * Created by gfp2ram on 9/6/2015.
 */
/*In My machine, hive context is always throwing OutofMemory Error*/
object JSONLoad {
  def main(args: Array[String]): Unit = {
    System.setProperty("hadoop.home.dir", "D:\\hadoop\\hadoop-common-2.2.0-bin-master\\")
    val conf = new SparkConf().setAppName("JSONSpark").setMaster("local")
    val sc = new SparkContext(conf)
    val sCtx = new SQLContext(sc)
        val inputData = sc.parallelize(
          """{ "head": { "link": [], "vars": ["film", "language", "editing", "cinematography", "distributor", "producer", "runtime", "starring", "writer", "allLyrics", "artist", "caption", "country", "director", "extra", "extraColumn", "genre", "hasPhotoCollection", "label", "length", "music", "name", "released", "studio"] },
      "results": { "distinct": false, "ordered": true, "bindings": [
        { "film": { "type": "uri", "value": "http://dbpedia.org/resource/Anbe_Vaa" }      , "language": { "type": "uri", "value": "http://dbpedia.org/resource/Tamil_language" }       , "editing": { "type": "literal", "xml:lang": "en", "value": "R. G. Gope" } , "cinematography": { "type": "literal", "xml:lang": "en", "value": "S. Maruthi Rao" }    , "distributor": { "type": "literal", "xml:lang": "en", "value": "AVM Productions" }       , "producer": { "type": "literal", "xml:lang": "en", "value": "M. Murugan" } , "runtime": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "10440.0" }   , "starring": { "type": "uri", "value": "http://dbpedia.org/resource/B._Saroja_Devi" }       , "writer": { "type": "literal", "xml:lang": "en", "value": "Aaroor Das" } , "allLyrics": { "type": "uri", "value": "http://dbpedia.org/resource/Vaali_(poet)" }  , "artist": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "caption": { "type": "literal", "xml:lang": "en", "value": "Theatrical release poster" }      , "country": { "type": "uri", "value": "http://dbpedia.org/resource/India" } , "director": { "type": "uri", "value": "http://dbpedia.org/resource/A._C._Tirulokchandar" } , "extra": { "type": "literal", "xml:lang": "en", "value": "P. Susheela and Chorus" }  , "extraColumn": { "type": "literal", "xml:lang": "en", "value": "Singer" }    , "genre": { "type": "uri", "value": "http://dbpedia.org/resource/Soundtrack" }    , "hasPhotoCollection": { "type": "uri", "value": "http://wifo5-03.informatik.uni-mannheim.de/flickrwrappr/photos/Anbe_Vaa" }   , "label": { "type": "uri", "value": "http://dbpedia.org/resource/Saregama" }     , "length": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "213.0" }     , "music": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "name": { "type": "literal", "xml:lang": "en", "value": "Anbe Vaa" }   , "released": { "type": "typed-literal", "datatype": "http://www.w3.org/2001/XMLSchema#date", "value": "1966-01-14" }     , "studio": { "type": "uri", "value": "http://dbpedia.org/resource/AVM_Productions" }},
        { "film": { "type": "uri", "value": "http://dbpedia.org/resource/Anbe_Vaa" }      , "language": { "type": "uri", "value": "http://dbpedia.org/resource/Tamil_language" }       , "editing": { "type": "literal", "xml:lang": "en", "value": "R. G. Gope" } , "cinematography": { "type": "literal", "xml:lang": "en", "value": "S. Maruthi Rao" }    , "distributor": { "type": "literal", "xml:lang": "en", "value": "AVM Productions" }       , "producer": { "type": "literal", "xml:lang": "en", "value": "M. S. Viswanathan" }  , "runtime": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "10440.0" }   , "starring": { "type": "uri", "value": "http://dbpedia.org/resource/B._Saroja_Devi" }       , "writer": { "type": "literal", "xml:lang": "en", "value": "Aaroor Das" } , "allLyrics": { "type": "uri", "value": "http://dbpedia.org/resource/Vaali_(poet)" }  , "artist": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "caption": { "type": "literal", "xml:lang": "en", "value": "Theatrical release poster" }      , "country": { "type": "uri", "value": "http://dbpedia.org/resource/India" } , "director": { "type": "uri", "value": "http://dbpedia.org/resource/A._C._Tirulokchandar" } , "extra": { "type": "uri", "value": "http://dbpedia.org/resource/T._M._Soundararajan" }  , "extraColumn": { "type": "literal", "xml:lang": "en", "value": "Singer" }   , "genre": { "type": "uri", "value": "http://dbpedia.org/resource/Soundtrack" }    , "hasPhotoCollection": { "type": "uri", "value": "http://wifo5-03.informatik.uni-mannheim.de/flickrwrappr/photos/Anbe_Vaa" }   , "label": { "type": "uri", "value": "http://dbpedia.org/resource/Saregama" }     , "length": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "245.0" }     , "music": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "name": { "type": "literal", "xml:lang": "en", "value": "Anbe Vaa" }   , "released": { "type": "typed-literal", "datatype": "http://www.w3.org/2001/XMLSchema#date", "value": "1966-01-14" }     , "studio": { "type": "uri", "value": "http://dbpedia.org/resource/AVM_Productions" }},
        { "film": { "type": "uri", "value": "http://dbpedia.org/resource/Anbe_Vaa" }      , "language": { "type": "uri", "value": "http://dbpedia.org/resource/Tamil_language" }       , "editing": { "type": "literal", "xml:lang": "en", "value": "R. G. Gope" } , "cinematography": { "type": "literal", "xml:lang": "en", "value": "S. Maruthi Rao" }    , "distributor": { "type": "literal", "xml:lang": "en", "value": "AVM Productions" }       , "producer": { "type": "literal", "xml:lang": "en", "value": "M. Murugan" } , "runtime": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "10440.0" }   , "starring": { "type": "uri", "value": "http://dbpedia.org/resource/M._G._Ramachandran" }   , "writer": { "type": "literal", "xml:lang": "en", "value": "Aaroor Das" } , "allLyrics": { "type": "uri", "value": "http://dbpedia.org/resource/Vaali_(poet)" }  , "artist": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "caption": { "type": "literal", "xml:lang": "en", "value": "Theatrical release poster" }      , "country": { "type": "uri", "value": "http://dbpedia.org/resource/India" } , "director": { "type": "uri", "value": "http://dbpedia.org/resource/A._C._Tirulokchandar" } , "extra": { "type": "literal", "xml:lang": "en", "value": "T. M. Soundararajan, P. Susheela, A. L. Raghavan, L. R. Eswari" }  , "extraColumn": { "type": "literal", "xml:lang": "en", "value": "Singer" }     , "genre": { "type": "uri", "value": "http://dbpedia.org/resource/Soundtrack" }    , "hasPhotoCollection": { "type": "uri", "value": "http://wifo5-03.informatik.uni-mannheim.de/flickrwrappr/photos/Anbe_Vaa" }   , "label": { "type": "uri", "value": "http://dbpedia.org/resource/Saregama" }     , "length": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "246.0" }     , "music": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "name": { "type": "literal", "xml:lang": "en", "value": "Anbe Vaa" }   , "released": { "type": "typed-literal", "datatype": "http://www.w3.org/2001/XMLSchema#date", "value": "1966-01-14" }     , "studio": { "type": "uri", "value": "http://dbpedia.org/resource/AVM_Productions" }},
        { "film": { "type": "uri", "value": "http://dbpedia.org/resource/Anbe_Vaa" }      , "language": { "type": "uri", "value": "http://dbpedia.org/resource/Tamil_language" }       , "editing": { "type": "literal", "xml:lang": "en", "value": "R. G. Gope" } , "cinematography": { "type": "literal", "xml:lang": "en", "value": "S. Maruthi Rao" }    , "distributor": { "type": "literal", "xml:lang": "en", "value": "AVM Productions" }       , "producer": { "type": "literal", "xml:lang": "en", "value": "M. Murugan" } , "runtime": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "10440.0" }   , "starring": { "type": "uri", "value": "http://dbpedia.org/resource/M._G._Ramachandran" }   , "writer": { "type": "literal", "xml:lang": "en", "value": "Aaroor Das" } , "allLyrics": { "type": "uri", "value": "http://dbpedia.org/resource/Vaali_(poet)" }  , "artist": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "caption": { "type": "literal", "xml:lang": "en", "value": "Theatrical release poster" }      , "country": { "type": "uri", "value": "http://dbpedia.org/resource/India" } , "director": { "type": "uri", "value": "http://dbpedia.org/resource/A._C._Tirulokchandar" } , "extra": { "type": "uri", "value": "http://dbpedia.org/resource/T._M._Soundararajan" }  , "extraColumn": { "type": "literal", "xml:lang": "en", "value": "Singer" }   , "genre": { "type": "uri", "value": "http://dbpedia.org/resource/Soundtrack" }    , "hasPhotoCollection": { "type": "uri", "value": "http://wifo5-03.informatik.uni-mannheim.de/flickrwrappr/photos/Anbe_Vaa" }   , "label": { "type": "uri", "value": "http://dbpedia.org/resource/Saregama" }     , "length": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "197.0" }     , "music": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "name": { "type": "literal", "xml:lang": "en", "value": "Anbe Vaa" }   , "released": { "type": "typed-literal", "datatype": "http://www.w3.org/2001/XMLSchema#date", "value": "1966-01-14" }     , "studio": { "type": "uri", "value": "http://dbpedia.org/resource/AVM_Productions" }},
        { "film": { "type": "uri", "value": "http://dbpedia.org/resource/Anbe_Vaa" }      , "language": { "type": "uri", "value": "http://dbpedia.org/resource/Tamil_language" }       , "editing": { "type": "literal", "xml:lang": "en", "value": "R. G. Gope" } , "cinematography": { "type": "literal", "xml:lang": "en", "value": "S. Maruthi Rao" }    , "distributor": { "type": "literal", "xml:lang": "en", "value": "AVM Productions" }       , "producer": { "type": "literal", "xml:lang": "en", "value": "M. Murugan" } , "runtime": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "10440.0" }   , "starring": { "type": "uri", "value": "http://dbpedia.org/resource/B._Saroja_Devi" }       , "writer": { "type": "literal", "xml:lang": "en", "value": "Aaroor Das" } , "allLyrics": { "type": "uri", "value": "http://dbpedia.org/resource/Vaali_(poet)" }  , "artist": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "caption": { "type": "literal", "xml:lang": "en", "value": "Theatrical release poster" }      , "country": { "type": "uri", "value": "http://dbpedia.org/resource/India" } , "director": { "type": "uri", "value": "http://dbpedia.org/resource/A._C._Tirulokchandar" } , "extra": { "type": "literal", "xml:lang": "en", "value": "T. M. Soundararajan, P. Susheela, A. L. Raghavan, L. R. Eswari" }  , "extraColumn": { "type": "literal", "xml:lang": "en", "value": "Singer" }     , "genre": { "type": "uri", "value": "http://dbpedia.org/resource/Soundtrack" }    , "hasPhotoCollection": { "type": "uri", "value": "http://wifo5-03.informatik.uni-mannheim.de/flickrwrappr/photos/Anbe_Vaa" }   , "label": { "type": "uri", "value": "http://dbpedia.org/resource/Saregama" }     , "length": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "79.0" }      , "music": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "name": { "type": "literal", "xml:lang": "en", "value": "Anbe Vaa" }   , "released": { "type": "typed-literal", "datatype": "http://www.w3.org/2001/XMLSchema#date", "value": "1966-01-14" }     , "studio": { "type": "uri", "value": "http://dbpedia.org/resource/AVM_Productions" }},
        { "film": { "type": "uri", "value": "http://dbpedia.org/resource/Anbe_Vaa" }      , "language": { "type": "uri", "value": "http://dbpedia.org/resource/Tamil_language" }       , "editing": { "type": "literal", "xml:lang": "en", "value": "R. G. Gope" } , "cinematography": { "type": "literal", "xml:lang": "en", "value": "S. Maruthi Rao" }    , "distributor": { "type": "literal", "xml:lang": "en", "value": "AVM Productions" }       , "producer": { "type": "literal", "xml:lang": "en", "value": "M. S. Viswanathan" }  , "runtime": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "10440.0" }   , "starring": { "type": "uri", "value": "http://dbpedia.org/resource/B._Saroja_Devi" }       , "writer": { "type": "literal", "xml:lang": "en", "value": "Aaroor Das" } , "allLyrics": { "type": "uri", "value": "http://dbpedia.org/resource/Vaali_(poet)" }  , "artist": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "caption": { "type": "literal", "xml:lang": "en", "value": "Theatrical release poster" }      , "country": { "type": "uri", "value": "http://dbpedia.org/resource/India" } , "director": { "type": "uri", "value": "http://dbpedia.org/resource/A._C._Tirulokchandar" } , "extra": { "type": "uri", "value": "http://dbpedia.org/resource/P._Susheela" }   , "extraColumn": { "type": "literal", "xml:lang": "en", "value": "Singer" }     , "genre": { "type": "uri", "value": "http://dbpedia.org/resource/Soundtrack" }    , "hasPhotoCollection": { "type": "uri", "value": "http://wifo5-03.informatik.uni-mannheim.de/flickrwrappr/photos/Anbe_Vaa" }   , "label": { "type": "uri", "value": "http://dbpedia.org/resource/Saregama" }     , "length": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "219.0" }     , "music": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "name": { "type": "literal", "xml:lang": "en", "value": "Anbe Vaa" }   , "released": { "type": "typed-literal", "datatype": "http://www.w3.org/2001/XMLSchema#date", "value": "1966-01-14" }     , "studio": { "type": "uri", "value": "http://dbpedia.org/resource/AVM_Productions" }},
        { "film": { "type": "uri", "value": "http://dbpedia.org/resource/Anbe_Vaa" }      , "language": { "type": "uri", "value": "http://dbpedia.org/resource/Tamil_language" }       , "editing": { "type": "literal", "xml:lang": "en", "value": "R. G. Gope" } , "cinematography": { "type": "literal", "xml:lang": "en", "value": "S. Maruthi Rao" }    , "distributor": { "type": "literal", "xml:lang": "en", "value": "AVM Productions" }       , "producer": { "type": "literal", "xml:lang": "en", "value": "M. S. Viswanathan" }  , "runtime": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "10440.0" }   , "starring": { "type": "uri", "value": "http://dbpedia.org/resource/B._Saroja_Devi" }       , "writer": { "type": "literal", "xml:lang": "en", "value": "Aaroor Das" } , "allLyrics": { "type": "uri", "value": "http://dbpedia.org/resource/Vaali_(poet)" }  , "artist": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "caption": { "type": "literal", "xml:lang": "en", "value": "Theatrical release poster" }      , "country": { "type": "uri", "value": "http://dbpedia.org/resource/India" } , "director": { "type": "uri", "value": "http://dbpedia.org/resource/A._C._Tirulokchandar" } , "extra": { "type": "literal", "xml:lang": "en", "value": "T. M. Soundararajan, P. Susheela" }  , "extraColumn": { "type": "literal", "xml:lang": "en", "value": "Singer" } , "genre": { "type": "uri", "value": "http://dbpedia.org/resource/Soundtrack" }  , "hasPhotoCollection": { "type": "uri", "value": "http://wifo5-03.informatik.uni-mannheim.de/flickrwrappr/photos/Anbe_Vaa" } , "label": { "type": "uri", "value": "http://dbpedia.org/resource/Saregama" }      , "length": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "197.0" }     , "music": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "name": { "type": "literal", "xml:lang": "en", "value": "Anbe Vaa" }   , "released": { "type": "typed-literal", "datatype": "http://www.w3.org/2001/XMLSchema#date", "value": "1966-01-14" }     , "studio": { "type": "uri", "value": "http://dbpedia.org/resource/AVM_Productions" }},
        { "film": { "type": "uri", "value": "http://dbpedia.org/resource/Anbe_Vaa" }      , "language": { "type": "uri", "value": "http://dbpedia.org/resource/Tamil_language" }       , "editing": { "type": "literal", "xml:lang": "en", "value": "R. G. Gope" } , "cinematography": { "type": "literal", "xml:lang": "en", "value": "S. Maruthi Rao" }    , "distributor": { "type": "literal", "xml:lang": "en", "value": "AVM Productions" }       , "producer": { "type": "literal", "xml:lang": "en", "value": "M. S. Viswanathan" }  , "runtime": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "10440.0" }   , "starring": { "type": "uri", "value": "http://dbpedia.org/resource/B._Saroja_Devi" }       , "writer": { "type": "literal", "xml:lang": "en", "value": "Aaroor Das" } , "allLyrics": { "type": "uri", "value": "http://dbpedia.org/resource/Vaali_(poet)" }  , "artist": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "caption": { "type": "literal", "xml:lang": "en", "value": "Theatrical release poster" }      , "country": { "type": "uri", "value": "http://dbpedia.org/resource/India" } , "director": { "type": "uri", "value": "http://dbpedia.org/resource/A._C._Tirulokchandar" } , "extra": { "type": "literal", "xml:lang": "en", "value": "A. L. Raghavan and Chorus" } , "extraColumn": { "type": "literal", "xml:lang": "en", "value": "Singer" } , "genre": { "type": "uri", "value": "http://dbpedia.org/resource/Soundtrack" }  , "hasPhotoCollection": { "type": "uri", "value": "http://wifo5-03.informatik.uni-mannheim.de/flickrwrappr/photos/Anbe_Vaa" } , "label": { "type": "uri", "value": "http://dbpedia.org/resource/Saregama" }      , "length": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "245.0" }     , "music": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "name": { "type": "literal", "xml:lang": "en", "value": "Anbe Vaa" }   , "released": { "type": "typed-literal", "datatype": "http://www.w3.org/2001/XMLSchema#date", "value": "1966-01-14" }     , "studio": { "type": "uri", "value": "http://dbpedia.org/resource/AVM_Productions" }},
        { "film": { "type": "uri", "value": "http://dbpedia.org/resource/Anbe_Vaa" }      , "language": { "type": "uri", "value": "http://dbpedia.org/resource/Tamil_language" }       , "editing": { "type": "literal", "xml:lang": "en", "value": "R. G. Gope" } , "cinematography": { "type": "literal", "xml:lang": "en", "value": "S. Maruthi Rao" }    , "distributor": { "type": "literal", "xml:lang": "en", "value": "AVM Productions" }       , "producer": { "type": "literal", "xml:lang": "en", "value": "M. S. Viswanathan" }  , "runtime": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "10440.0" }   , "starring": { "type": "uri", "value": "http://dbpedia.org/resource/M._G._Ramachandran" }   , "writer": { "type": "literal", "xml:lang": "en", "value": "Aaroor Das" } , "allLyrics": { "type": "uri", "value": "http://dbpedia.org/resource/Vaali_(poet)" }  , "artist": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "caption": { "type": "literal", "xml:lang": "en", "value": "Theatrical release poster" }      , "country": { "type": "uri", "value": "http://dbpedia.org/resource/India" } , "director": { "type": "uri", "value": "http://dbpedia.org/resource/A._C._Tirulokchandar" } , "extra": { "type": "literal", "xml:lang": "en", "value": "T. M. Soundararajan, P. Susheela, A. L. Raghavan, L. R. Eswari" }  , "extraColumn": { "type": "literal", "xml:lang": "en", "value": "Singer" }     , "genre": { "type": "uri", "value": "http://dbpedia.org/resource/Soundtrack" }    , "hasPhotoCollection": { "type": "uri", "value": "http://wifo5-03.informatik.uni-mannheim.de/flickrwrappr/photos/Anbe_Vaa" }   , "label": { "type": "uri", "value": "http://dbpedia.org/resource/Saregama" }     , "length": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "219.0" }     , "music": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "name": { "type": "literal", "xml:lang": "en", "value": "Anbe Vaa" }   , "released": { "type": "typed-literal", "datatype": "http://www.w3.org/2001/XMLSchema#date", "value": "1966-01-14" }     , "studio": { "type": "uri", "value": "http://dbpedia.org/resource/AVM_Productions" }},
        { "film": { "type": "uri", "value": "http://dbpedia.org/resource/Anbe_Vaa" }      , "language": { "type": "uri", "value": "http://dbpedia.org/resource/Tamil_language" }       , "editing": { "type": "literal", "xml:lang": "en", "value": "R. G. Gope" } , "cinematography": { "type": "literal", "xml:lang": "en", "value": "S. Maruthi Rao" }    , "distributor": { "type": "literal", "xml:lang": "en", "value": "AVM Productions" }       , "producer": { "type": "literal", "xml:lang": "en", "value": "M. Murugan" } , "runtime": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "10440.0" }   , "starring": { "type": "uri", "value": "http://dbpedia.org/resource/B._Saroja_Devi" }       , "writer": { "type": "literal", "xml:lang": "en", "value": "Aaroor Das" } , "allLyrics": { "type": "uri", "value": "http://dbpedia.org/resource/Vaali_(poet)" }  , "artist": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "caption": { "type": "literal", "xml:lang": "en", "value": "Theatrical release poster" }      , "country": { "type": "uri", "value": "http://dbpedia.org/resource/India" } , "director": { "type": "uri", "value": "http://dbpedia.org/resource/A._C._Tirulokchandar" } , "extra": { "type": "uri", "value": "http://dbpedia.org/resource/T._M._Soundararajan" }  , "extraColumn": { "type": "literal", "xml:lang": "en", "value": "Singer" }   , "genre": { "type": "uri", "value": "http://dbpedia.org/resource/Soundtrack" }    , "hasPhotoCollection": { "type": "uri", "value": "http://wifo5-03.informatik.uni-mannheim.de/flickrwrappr/photos/Anbe_Vaa" }   , "label": { "type": "uri", "value": "http://dbpedia.org/resource/Saregama" }     , "length": { "type": "typed-literal", "datatype": "http://dbpedia.org/datatype/second", "value": "79.0" }      , "music": { "type": "uri", "value": "http://dbpedia.org/resource/M._S._Viswanathan" }    , "name": { "type": "literal", "xml:lang": "en", "value": "Anbe Vaa" }   , "released": { "type": "typed-literal", "datatype": "http://www.w3.org/2001/XMLSchema#date", "value": "1966-01-14" }     , "studio": { "type": "uri", "value": "http://dbpedia.org/resource/AVM_Productions" }} ] } }
          """ :: Nil)
        //
        val JSONData = sCtx.read.json(inputData)
        //JSONData.printSchema()
        JSONData.registerTempTable("movietable")
        val res = sCtx.sql("select distinct results.bindings.language.value[0],results.bindings.country.value[0]," +
          "results.bindings.editing.value[0],results.bindings.cinematography.value[0],results.bindings.distributor.value[0]," +
          "results.bindings.editing.value[0],results.bindings.producer.value[0],results.bindings.runtime.value[0],results.bindings.starring.value[0]," +
          "results.bindings.writer.value[0],results.bindings.allLyrics.value[0],results.bindings.artist.value[0],results.bindings.caption.value[0]," +
          "results.bindings.cinematography.value[0],results.bindings.country.value[0],results.bindings.director.value[0]," +
          "results.bindings.distributor.value[0],results.bindings.editing.value[0],results.bindings.extra.value[0]," +
          "results.bindings.extraColumn.value[0],results.bindings.genre.value[0],results.bindings.hasPhotoCollection.value[0]," +
          "results.bindings.label.value[0],results.bindings.language.value[0],results.bindings.length.value[0]," +
          "results.bindings.music.value[0],results.bindings.name.value[0],results.bindings.producer.value[0]," +
          "results.bindings.released.value[0],results.bindings.runtime.value[0],results.bindings.starring.value[0]," +
          "results.bindings.studio.value[0] from movietable limit 1")
        JSONData.printSchema()

//    val inputData = sc.parallelize(
//      """{
//"firstName": "John",
//"lastName": "Smith",
//"age": 25,
//"address":
//{
//"streetAddress": "21 2nd Street",
//"city": "New York",
//"state": "NY",
//"postalCode": "10021"
//},
//"phoneNumber":
//[
//{
//"type": "home",
//"number": "212 555-1234"
//},
//{
//"type": "fax",
//"number": "646 555-4567"
//}
//]
//}""" :: Nil)
//    val JSONData = sCtx.read.json(inputData)
//    JSONData.registerTempTable("customerform")
//    val queryOutput = sCtx.sql("select firstName,lastName,age,address.streetAddress,address.city,address.state,address.postalCode,phoneNumber.number[0] as homePhone from customerform")
//    queryOutput.explain()
//    JSONData.explain()

  }
}

